### ISSUE TITLE
Invalid when you use packr2 and run it under windows

### ISSUE THREAD

**Issue by menta2k** [vicanso/elton-static-serve#1]
#### Issue description
Invaid path when you use packr2  as static content and run it under windows

#### Steps to reproduce the issue

pack your resources packr2 and use it in elton-static-serve with config.Path = /static
a single resource path looks like 
/css/main.74968888.chunk.css

after  calling under windows 

https://github.com/vicanso/elton-static-serve/blob/7ec20104ea8aed0d4e8fb6d3a490e4ef3fbe7832/static_serve.go#L188

resource will become :

\static\css\main.74968888.chunk.css

and the flowing check always fails 

https://github.com/vicanso/elton-static-serve/blob/7ec20104ea8aed0d4e8fb6d3a490e4ef3fbe7832/static_serve.go#L190

**Comment by vicanso** [comment]
I had fixed it, please have a try.

**Comment by Menta2L** [comment]
Works perfectly :)
